package com.philips.easykey.lock.utils.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.philips.easykey.lock.publiclibrary.bean.ProductInfo;
import com.philips.easykey.lock.publiclibrary.bean.WifiLockInfo;
import com.philips.easykey.lock.utils.greenDao.bean.BleLockServiceInfo;
import com.philips.easykey.lock.utils.greenDao.bean.ClothesHangerMachineAllBean;
import com.philips.easykey.lock.utils.greenDao.bean.DBOpenLockRecord;
import com.philips.easykey.lock.utils.greenDao.bean.DevicePower;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayBaseInfo;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayLockAlarmEventDao;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayLockBaseInfo;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayLockPwd;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayLockRecord;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayLockServiceInfo;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayPasswordPlanBean;
import com.philips.easykey.lock.utils.greenDao.bean.GatewayServiceInfo;
import com.philips.easykey.lock.utils.greenDao.bean.HistoryInfo;

import com.philips.easykey.lock.utils.greenDao.db.ProductInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.WifiLockInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.BleLockServiceInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.ClothesHangerMachineAllBeanDao;
import com.philips.easykey.lock.utils.greenDao.db.DBOpenLockRecordDao;
import com.philips.easykey.lock.utils.greenDao.db.DevicePowerDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayBaseInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayLockAlarmEventDaoDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayLockBaseInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayLockPwdDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayLockRecordDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayLockServiceInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayPasswordPlanBeanDao;
import com.philips.easykey.lock.utils.greenDao.db.GatewayServiceInfoDao;
import com.philips.easykey.lock.utils.greenDao.db.HistoryInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productInfoDaoConfig;
    private final DaoConfig wifiLockInfoDaoConfig;
    private final DaoConfig bleLockServiceInfoDaoConfig;
    private final DaoConfig clothesHangerMachineAllBeanDaoConfig;
    private final DaoConfig dBOpenLockRecordDaoConfig;
    private final DaoConfig devicePowerDaoConfig;
    private final DaoConfig gatewayBaseInfoDaoConfig;
    private final DaoConfig gatewayLockAlarmEventDaoDaoConfig;
    private final DaoConfig gatewayLockBaseInfoDaoConfig;
    private final DaoConfig gatewayLockPwdDaoConfig;
    private final DaoConfig gatewayLockRecordDaoConfig;
    private final DaoConfig gatewayLockServiceInfoDaoConfig;
    private final DaoConfig gatewayPasswordPlanBeanDaoConfig;
    private final DaoConfig gatewayServiceInfoDaoConfig;
    private final DaoConfig historyInfoDaoConfig;

    private final ProductInfoDao productInfoDao;
    private final WifiLockInfoDao wifiLockInfoDao;
    private final BleLockServiceInfoDao bleLockServiceInfoDao;
    private final ClothesHangerMachineAllBeanDao clothesHangerMachineAllBeanDao;
    private final DBOpenLockRecordDao dBOpenLockRecordDao;
    private final DevicePowerDao devicePowerDao;
    private final GatewayBaseInfoDao gatewayBaseInfoDao;
    private final GatewayLockAlarmEventDaoDao gatewayLockAlarmEventDaoDao;
    private final GatewayLockBaseInfoDao gatewayLockBaseInfoDao;
    private final GatewayLockPwdDao gatewayLockPwdDao;
    private final GatewayLockRecordDao gatewayLockRecordDao;
    private final GatewayLockServiceInfoDao gatewayLockServiceInfoDao;
    private final GatewayPasswordPlanBeanDao gatewayPasswordPlanBeanDao;
    private final GatewayServiceInfoDao gatewayServiceInfoDao;
    private final HistoryInfoDao historyInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productInfoDaoConfig = daoConfigMap.get(ProductInfoDao.class).clone();
        productInfoDaoConfig.initIdentityScope(type);

        wifiLockInfoDaoConfig = daoConfigMap.get(WifiLockInfoDao.class).clone();
        wifiLockInfoDaoConfig.initIdentityScope(type);

        bleLockServiceInfoDaoConfig = daoConfigMap.get(BleLockServiceInfoDao.class).clone();
        bleLockServiceInfoDaoConfig.initIdentityScope(type);

        clothesHangerMachineAllBeanDaoConfig = daoConfigMap.get(ClothesHangerMachineAllBeanDao.class).clone();
        clothesHangerMachineAllBeanDaoConfig.initIdentityScope(type);

        dBOpenLockRecordDaoConfig = daoConfigMap.get(DBOpenLockRecordDao.class).clone();
        dBOpenLockRecordDaoConfig.initIdentityScope(type);

        devicePowerDaoConfig = daoConfigMap.get(DevicePowerDao.class).clone();
        devicePowerDaoConfig.initIdentityScope(type);

        gatewayBaseInfoDaoConfig = daoConfigMap.get(GatewayBaseInfoDao.class).clone();
        gatewayBaseInfoDaoConfig.initIdentityScope(type);

        gatewayLockAlarmEventDaoDaoConfig = daoConfigMap.get(GatewayLockAlarmEventDaoDao.class).clone();
        gatewayLockAlarmEventDaoDaoConfig.initIdentityScope(type);

        gatewayLockBaseInfoDaoConfig = daoConfigMap.get(GatewayLockBaseInfoDao.class).clone();
        gatewayLockBaseInfoDaoConfig.initIdentityScope(type);

        gatewayLockPwdDaoConfig = daoConfigMap.get(GatewayLockPwdDao.class).clone();
        gatewayLockPwdDaoConfig.initIdentityScope(type);

        gatewayLockRecordDaoConfig = daoConfigMap.get(GatewayLockRecordDao.class).clone();
        gatewayLockRecordDaoConfig.initIdentityScope(type);

        gatewayLockServiceInfoDaoConfig = daoConfigMap.get(GatewayLockServiceInfoDao.class).clone();
        gatewayLockServiceInfoDaoConfig.initIdentityScope(type);

        gatewayPasswordPlanBeanDaoConfig = daoConfigMap.get(GatewayPasswordPlanBeanDao.class).clone();
        gatewayPasswordPlanBeanDaoConfig.initIdentityScope(type);

        gatewayServiceInfoDaoConfig = daoConfigMap.get(GatewayServiceInfoDao.class).clone();
        gatewayServiceInfoDaoConfig.initIdentityScope(type);

        historyInfoDaoConfig = daoConfigMap.get(HistoryInfoDao.class).clone();
        historyInfoDaoConfig.initIdentityScope(type);

        productInfoDao = new ProductInfoDao(productInfoDaoConfig, this);
        wifiLockInfoDao = new WifiLockInfoDao(wifiLockInfoDaoConfig, this);
        bleLockServiceInfoDao = new BleLockServiceInfoDao(bleLockServiceInfoDaoConfig, this);
        clothesHangerMachineAllBeanDao = new ClothesHangerMachineAllBeanDao(clothesHangerMachineAllBeanDaoConfig, this);
        dBOpenLockRecordDao = new DBOpenLockRecordDao(dBOpenLockRecordDaoConfig, this);
        devicePowerDao = new DevicePowerDao(devicePowerDaoConfig, this);
        gatewayBaseInfoDao = new GatewayBaseInfoDao(gatewayBaseInfoDaoConfig, this);
        gatewayLockAlarmEventDaoDao = new GatewayLockAlarmEventDaoDao(gatewayLockAlarmEventDaoDaoConfig, this);
        gatewayLockBaseInfoDao = new GatewayLockBaseInfoDao(gatewayLockBaseInfoDaoConfig, this);
        gatewayLockPwdDao = new GatewayLockPwdDao(gatewayLockPwdDaoConfig, this);
        gatewayLockRecordDao = new GatewayLockRecordDao(gatewayLockRecordDaoConfig, this);
        gatewayLockServiceInfoDao = new GatewayLockServiceInfoDao(gatewayLockServiceInfoDaoConfig, this);
        gatewayPasswordPlanBeanDao = new GatewayPasswordPlanBeanDao(gatewayPasswordPlanBeanDaoConfig, this);
        gatewayServiceInfoDao = new GatewayServiceInfoDao(gatewayServiceInfoDaoConfig, this);
        historyInfoDao = new HistoryInfoDao(historyInfoDaoConfig, this);

        registerDao(ProductInfo.class, productInfoDao);
        registerDao(WifiLockInfo.class, wifiLockInfoDao);
        registerDao(BleLockServiceInfo.class, bleLockServiceInfoDao);
        registerDao(ClothesHangerMachineAllBean.class, clothesHangerMachineAllBeanDao);
        registerDao(DBOpenLockRecord.class, dBOpenLockRecordDao);
        registerDao(DevicePower.class, devicePowerDao);
        registerDao(GatewayBaseInfo.class, gatewayBaseInfoDao);
        registerDao(GatewayLockAlarmEventDao.class, gatewayLockAlarmEventDaoDao);
        registerDao(GatewayLockBaseInfo.class, gatewayLockBaseInfoDao);
        registerDao(GatewayLockPwd.class, gatewayLockPwdDao);
        registerDao(GatewayLockRecord.class, gatewayLockRecordDao);
        registerDao(GatewayLockServiceInfo.class, gatewayLockServiceInfoDao);
        registerDao(GatewayPasswordPlanBean.class, gatewayPasswordPlanBeanDao);
        registerDao(GatewayServiceInfo.class, gatewayServiceInfoDao);
        registerDao(HistoryInfo.class, historyInfoDao);
    }
    
    public void clear() {
        productInfoDaoConfig.clearIdentityScope();
        wifiLockInfoDaoConfig.clearIdentityScope();
        bleLockServiceInfoDaoConfig.clearIdentityScope();
        clothesHangerMachineAllBeanDaoConfig.clearIdentityScope();
        dBOpenLockRecordDaoConfig.clearIdentityScope();
        devicePowerDaoConfig.clearIdentityScope();
        gatewayBaseInfoDaoConfig.clearIdentityScope();
        gatewayLockAlarmEventDaoDaoConfig.clearIdentityScope();
        gatewayLockBaseInfoDaoConfig.clearIdentityScope();
        gatewayLockPwdDaoConfig.clearIdentityScope();
        gatewayLockRecordDaoConfig.clearIdentityScope();
        gatewayLockServiceInfoDaoConfig.clearIdentityScope();
        gatewayPasswordPlanBeanDaoConfig.clearIdentityScope();
        gatewayServiceInfoDaoConfig.clearIdentityScope();
        historyInfoDaoConfig.clearIdentityScope();
    }

    public ProductInfoDao getProductInfoDao() {
        return productInfoDao;
    }

    public WifiLockInfoDao getWifiLockInfoDao() {
        return wifiLockInfoDao;
    }

    public BleLockServiceInfoDao getBleLockServiceInfoDao() {
        return bleLockServiceInfoDao;
    }

    public ClothesHangerMachineAllBeanDao getClothesHangerMachineAllBeanDao() {
        return clothesHangerMachineAllBeanDao;
    }

    public DBOpenLockRecordDao getDBOpenLockRecordDao() {
        return dBOpenLockRecordDao;
    }

    public DevicePowerDao getDevicePowerDao() {
        return devicePowerDao;
    }

    public GatewayBaseInfoDao getGatewayBaseInfoDao() {
        return gatewayBaseInfoDao;
    }

    public GatewayLockAlarmEventDaoDao getGatewayLockAlarmEventDaoDao() {
        return gatewayLockAlarmEventDaoDao;
    }

    public GatewayLockBaseInfoDao getGatewayLockBaseInfoDao() {
        return gatewayLockBaseInfoDao;
    }

    public GatewayLockPwdDao getGatewayLockPwdDao() {
        return gatewayLockPwdDao;
    }

    public GatewayLockRecordDao getGatewayLockRecordDao() {
        return gatewayLockRecordDao;
    }

    public GatewayLockServiceInfoDao getGatewayLockServiceInfoDao() {
        return gatewayLockServiceInfoDao;
    }

    public GatewayPasswordPlanBeanDao getGatewayPasswordPlanBeanDao() {
        return gatewayPasswordPlanBeanDao;
    }

    public GatewayServiceInfoDao getGatewayServiceInfoDao() {
        return gatewayServiceInfoDao;
    }

    public HistoryInfoDao getHistoryInfoDao() {
        return historyInfoDao;
    }

}
